const ACCOUNT_DECLARED = 'ACCOUNT_DECLARED'

const ACCOUNT_CREDITED = 'ACCOUNT_CREDITED'

const ACCOUNT_DEBITED = 'ACCOUNT_DEBITED'

module.exports = {
  ACCOUNT_DECLARED,
  ACCOUNT_CREDITED,
  ACCOUNT_DEBITED
}
