const ACCOUNT_DECLARED = 'ACCOUNT_DECLARED'

const ACCOUNT_CREDITED = 'ACCOUNT_CREDITED'

const ACCOUNT_DEBITED = 'ACCOUNT_DEBITED'

const ACCOUNT_UNDECLARED = 'ACCOUNT_UNDECLARED'

const AMOUNT_TRANSFERRED = 'AMOUNT_TRANSFERRED'

const REQUEST_FORBIDDEN = 'REQUEST_FORBIDDEN'

module.exports = {
  ACCOUNT_DECLARED,
  ACCOUNT_CREDITED,
  ACCOUNT_DEBITED,
  ACCOUNT_UNDECLARED,
  AMOUNT_TRANSFERRED,
  REQUEST_FORBIDDEN
}
